name: Build on Windows
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build-win:
    runs-on: windows-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install Choco Tools
        run: |
          choco install 7zip.install wget -y

      - name: Download LLVM and Clang
        run: |
          wget https://github.com/llvm/llvm-project/releases/download/llvmorg-18.1.8/clang+llvm-18.1.8-x86_64-pc-windows-msvc.tar.xz -O llvm.tar.xz

      - name: Install LLVM and Clang
        run: |
          7z x llvm.tar.xz -so | 7z x -aoa -si -ttar -o${{ runner.temp }}
          dir ${{ runner.temp }}
          mv ${{ runner.temp }}/clang+llvm-18.1.8-x86_64-pc-windows-msvc ${{ runner.temp }}/llvm
        shell: pwsh

      - name: Add LLVM to PATH
        run: |
          echo "${{ runner.temp }}/llvm/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Verify LLVM Path
        run: |
          echo $env:PATH
          which clang
          clang --version
          clang-tidy --version
          clang-format --version
        shell: pwsh

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install MSYS2
        uses: msys2/setup-msys2@v2
        with:
          install: mingw-w64-x86_64-gmp

      - name: Add MSYS2 to PATH
        run: echo "C:/msys64/mingw64/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Build Repo
        shell: pwsh
        run: |
          cmake -DCMAKE_BUILD_TYPE:STRING=Release -DLINK_LLVM_DYLIB=ON -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DLLVM_BUILD_DIR=${{ runner.temp }}/llvm -B build
          cmake --build build -j16
          echo "$(pwd)/build/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      
      - name: Test Binary
        shell: pwsh
        run: |
          which knight
          knight --help

      - name: Unit Tests
        shell: pwsh
        run: |
          python3 scripts/unittest run test/testcase/
