name: Build on Mac OS
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  build-mac:
    runs-on: macos-latest
    env:
      LDFLAGS: "-L/opt/homebrew/opt/llvm@18/lib"
      CPPFLAGS: "-I/opt/homebrew/opt/llvm@18/include"
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          brew update
          brew install \
            cmake gmp \
            sqlite\
            llvm@18
          echo "/opt/homebrew/opt/llvm@18/bin" >> $GITHUB_PATH

      - name: Test LLVM
        run: |
          which clang
          clang --version
          llvm-config --bindir

      - name: Spell Check
        uses: crate-ci/typos@v1.24.3

      - name: Clang Format
        run: |
          chmod +x scripts/run-clang-format
          scripts/run-clang-format

      - name: Build Repo
        run: |
          cmake -DCMAKE_BUILD_TYPE:STRING=Release \
           -DLINK_LLVM_DYLIB=ON -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE \
           -DCMAKE_INSTALL_PREFIX="/opt/knight" -DLLVM_BUILD_DIR="/opt/homebrew/opt/llvm@18" \
           -B build
          cmake --build build -j16
          echo $(pwd)/build/bin >> $GITHUB_PATH

      - name: Test Binary
        run: |
          knight --help

      - name: Unit Tests
        run: |
          chmod +x scripts/unittest
          scripts/unittest run test/testcase/
